[package]
name = "airmedia"
version = "0.1.4"
authors = ["Andrew White <aeewhite@gmail.com>"]

[dependencies]
quicli = "0.2"
indicatif = "0.9.0"
regex = "1.0.0"
reqwest = { git = "https://github.com/scottschroeder/reqwest", branch = "noverify" }